### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by d3nish** [idl3r/GhidraVmlinuxLoader#1]
It's possible so you can look on disassembling qcom bootloader script?
I have a [script](https://github.com/Surge1223/ida-mbn-sbl-loader) but I can't actually disassemble any function in Ida with it

And is it possible to somehow get back stripped symbols from lk?

Mbn files I mean, no proper guide to disassemble them in ida here is some links to mbn files please have a look on them
[mbn files](https://osdn.net/projects/xiaomifirmwareupdater/storage/Stable/V10/sagit/fw_sagit_miui_MI6Global_V10.0.1.0.OCAMIFH_1f4296c44e_8.0.zip)

**Comment by idl3r** [comment]
I guess you are referring to edk2? Well it's not my field but I can tell that it is compressed (lzma) bundle in abl.elf. Loader for bootloader is definitely interesting, but I believe there is no straightforward way to extract them like kernel. If you are interested, you may try to write one by yourself.

mbn are just images. I think any dissamble tool would be for mbn files for a specific purpose.

**Comment by d3nish** [comment]
Anyway to extract it with binwalk ? So I can load it in ida

**Comment by idl3r** [comment]
If you want to dig into this area, you need to do some research yourself.

**Comment by d3nish** [comment]
I did man but it's damn hard and I have no experience, so I thought I can get some help from you
