### ISSUE TITLE
Extension built for 9.0, but Ghidra is now 9.1-BETA

### ISSUE THREAD

**Issue by zdrouse** [idl3r/GhidraVmlinuxLoader#2]
Plans to update for 9.1 ?

Guess I will try previous Ghidra release

**Comment by zdrouse** [comment]
I've installed for 9.0 and don't see Vmlinux Loader as a format option for my Android kernel boot image.

![Alt Text](https://i.imgur.com/zeTy41s.png)

And when I go to the Extensions again, it's unselected.  I select and Ghidra prompts for restart but it doesn't stay.  The Sample extensions stay.

![Alt Text](https://i.imgur.com/FaFEm2t.png)

**Comment by idl3r** [comment]
This is merely a json parser for the output of [droidimg](https://github.com/nforest/droidimg), I believe there should be no problem to build with any further version by just updating corresponding properties. I'm not using Ghidra recently so please let me know the result if you'd like to try.

The extension installation problem seems to be with your Ghidra installation. Never seen this problem before.

**Comment by zdrouse** [comment]
@idl3r Thanks, I'll try doing that and use with Ghidra 9.1-BETA

**Comment by dobo90** [comment]
Hi there.

Few days ago I've managed to adjust this extension to Ghidra's 9.1 as there were some API changes. You can find it on [https://github.com/dobo90/GhidraVmlinuxLoader/tree/ghidra_9.1-BETA](https://github.com/dobo90/GhidraVmlinuxLoader/tree/ghidra_9.1-BETA).

@zdrouse did you compile plugin using gradle? If not, you have to:
```
cd /path/to/extension
export GHIDRA_INSTALL_DIR=/path/to/ghidra 
gradle
```

Btw, today final Ghidra 9.1 has been released. I haven't tested my changes with it.

**Comment by zdrouse** [comment]
Hey @dobo90, thanks for this!  I'm gonna give it a go - I haven't tried changing the properties myself yet.

**Comment by idl3r** [comment]
@dobo90 Thanks for the input!

**Comment by zdrouse** [comment]
@dobo90 
Hey there, I tried doing the build with your modifications, but for 9.1
Got an error for class version, I'm gonna try figuring out how to handle that but maybe you know more about it.

![class version failure](https://i.imgur.com/6cofhwY.png)

EDIT:  I should also mention that I got this same error when trying the modifications you had for the BETA build as well.

**Comment by idl3r** [comment]
@zdrouse most likely your jdk version is too low.

**Comment by dobo90** [comment]
@zdrouse I'm using Arch Linux with JDK11 and I have no issues with building. I've uploaded compiled version for Ghidra 9.1. You can check it on:
https://github.com/dobo90/GhidraVmlinuxLoader/releases/tag/0.1-ghidra_9.1
Hopefully it will work for you.

**Comment by idl3r** [comment]
Updated the code to match latest Ghidra 10.4. Issue closed.
